# Generated by Django 2.0.7 on 2019-12-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上线')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('intor', models.TextField(max_length=250)),
                ('brief', models.TextField(max_length=100)),
                ('nums', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '俱乐部表',
                'db_table': 'zx_club',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='0', max_length=30)),
                ('image_url', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='club.Images'),
        ),
    ]
