# Generated by Django 2.0.7 on 2019-12-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_url',
            field=models.ImageField(upload_to='all'),
        ),
    ]
