# Generated by Django 2.0.7 on 2019-12-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上线')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='车名')),
                ('brand', models.CharField(max_length=30, verbose_name='品牌')),
                ('model', models.CharField(max_length=30, verbose_name='型号')),
                ('type', models.SmallIntegerField(choices=[(0, '商务车'), (4, '跑车'), (1, 'SUV'), (3, '豪华车'), (2, '电动车')], verbose_name='车辆类型')),
                ('tab', models.SmallIntegerField(choices=[(2, '普通'), (0, '热门'), (3, '珍贵'), (1, '限量')], verbose_name='车辆标签')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上线')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('intor', models.CharField(max_length=500, verbose_name='详细描述')),
                ('environmental', models.SmallIntegerField(choices=[(1, '国VI'), (0, '国III'), (3, '国IV'), (2, '国V')], verbose_name='环保标准')),
                ('power', models.IntegerField(verbose_name='功率')),
                ('engine', models.CharField(max_length=30, verbose_name='发动机')),
                ('transmission', models.CharField(max_length=30, verbose_name='变速箱')),
                ('structure', models.CharField(max_length=30, verbose_name='几座几门')),
                ('size', models.CharField(max_length=30, verbose_name='长宽高')),
                ('accelerate', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='百公里加速')),
                ('max_speed', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='极限速度')),
                ('oil', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='油耗')),
                ('url', models.CharField(max_length=50, verbose_name='视频链接')),
                ('quality', models.IntegerField(verbose_name='质保/月')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('p_order', models.IntegerField(default=0)),
                ('price_cat', models.CharField(default=0, max_length=20, verbose_name='价格区间')),
                ('else_cat', models.CharField(default=0, max_length=20, verbose_name='自定义分类')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('out_trade_no', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(max_length=64, null=True, verbose_name='流水号')),
                ('order_id', models.AutoField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('active', '活动订单'), ('dead', '作废订单'), ('finish', '已完成订单')], default='active', max_length=50)),
                ('pay_status', models.SmallIntegerField(choices=[(0, '未付款'), (1, '已付款')], default=0)),
                ('payed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pay_app', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('memo', models.CharField(default=0, max_length=200)),
                ('consignee_name', models.CharField(default=0, max_length=200)),
                ('consignee_area', models.CharField(default=0, max_length=200)),
                ('consignee_address', models.CharField(default=0, max_length=200)),
                ('consignee_zip', models.CharField(default=0, max_length=200)),
                ('consignee_mobile', models.CharField(default=0, max_length=200)),
                ('car', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='car.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上线')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
