# Generated by Django 2.0.7 on 2019-12-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tab',
            field=models.SmallIntegerField(choices=[(2, '普通'), (1, '限量'), (3, '珍贵'), (0, '热门')], verbose_name='车辆标签'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.SmallIntegerField(choices=[(2, '电动车'), (0, '商务车'), (3, '豪华车'), (4, '跑车'), (1, 'SUV')], verbose_name='车辆类型'),
        ),
        migrations.AlterField(
            model_name='car_detail',
            name='environmental',
            field=models.SmallIntegerField(choices=[(3, '国IV'), (1, '国VI'), (2, '国V'), (0, '国III')], verbose_name='环保标准'),
        ),
    ]
