# Generated by Django 2.0.7 on 2019-12-24 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Images'),
        ),
        migrations.AddField(
            model_name='car',
            name='detail',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='car.Car_detail'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='club.Images'),
        ),
        migrations.AddField(
            model_name='car',
            name='stock',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='car.Stock'),
        ),
    ]
