# Generated by Django 2.0.7 on 2019-12-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20191224_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tab',
            field=models.SmallIntegerField(choices=[(1, '限量'), (3, '珍贵'), (0, '热门'), (2, '普通')], verbose_name='车辆标签'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.SmallIntegerField(choices=[(4, '跑车'), (1, 'SUV'), (0, '商务车'), (2, '电动车'), (3, '豪华车')], verbose_name='车辆类型'),
        ),
        migrations.AlterField(
            model_name='car_detail',
            name='environmental',
            field=models.SmallIntegerField(choices=[(0, '国III'), (1, '国VI'), (3, '国IV'), (2, '国V')], verbose_name='环保标准'),
        ),
    ]
