# Generated by Django 2.0.7 on 2019-12-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20191223_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tab',
            field=models.SmallIntegerField(choices=[(1, '限量'), (2, '普通'), (3, '珍贵'), (0, '热门')], verbose_name='车辆标签'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'SUV'), (3, '豪华车'), (4, '跑车'), (2, '电动车'), (0, '商务车')], verbose_name='车辆类型'),
        ),
        migrations.AlterField(
            model_name='car_detail',
            name='environmental',
            field=models.SmallIntegerField(choices=[(1, '国VI'), (3, '国IV'), (2, '国V'), (0, '国III')], verbose_name='环保标准'),
        ),
    ]
