# Generated by Django 2.0.7 on 2019-12-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20191223_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tab',
            field=models.SmallIntegerField(choices=[(0, '热门'), (3, '珍贵'), (1, '限量'), (2, '普通')], verbose_name='车辆标签'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.SmallIntegerField(choices=[(2, '电动车'), (0, '商务车'), (4, '跑车'), (3, '豪华车'), (1, 'SUV')], verbose_name='车辆类型'),
        ),
        migrations.AlterField(
            model_name='car_detail',
            name='environmental',
            field=models.SmallIntegerField(choices=[(0, '国III'), (2, '国V'), (1, '国VI'), (3, '国IV')], verbose_name='环保标准'),
        ),
    ]
